Improving logging messages for askbot backend
chaoss/grimoirelab-perceval pull request #693
Opened 2020-10-01 20:30 UTC by nworb95

Had a lot of trouble with setup so wasn't able to dig into this much.  Looking to circle back on my personal computer which is an ubuntu machine.

Let me know if these are ok as `logging.info` or if you think they are more appropriate as `logging.debug`!

2020-10-01 20:35 UTC, nworb95 commented
I'm not clear on why the travis-ci check was cancelled!

2020-10-01 21:50 UTC, sduenas requested changes
Thanks for your contribution. Just some comments beside the specific notes I added.

1. Instead of `logging` use `logger` object.
2. Remove `!` character to make messages more formal.
3. Can you improve your commit message? Follow this guidelines if possible: https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages

2020-10-01 21:50 UTC, sduenas commented on perceval/backends/core/askbot.py
> +        logging.info(f"{str(len(bs_answers))} answers found!")
I think this works better as a `debug` message.

2020-10-01 21:50 UTC, sduenas commented on perceval/backends/core/askbot.py
> +            logging.info(f"User info: {update_info}")
I think we can avoid this message because it will print the whole user information to the output.

2020-10-01 21:50 UTC, sduenas commented on perceval/backends/core/askbot.py
> +        logging.info("Answers parsed!")
This should be a `debug` message too.

2020-10-01 21:50 UTC, sduenas commented on perceval/backends/core/askbot.py
> +        logging.info("Container info parsed!")
This works better as a debug message.

2020-10-01 21:50 UTC, sduenas commented on perceval/backends/core/askbot.py
> +        logging.info("Retrieving question pages!")
I think also think this a `debug` message.

2020-10-02 13:04 UTC, nworb95 commented
Thanks, Santiago!  Once I get it running on my Ubuntu I will make these changes.  Appreciate the thorough feedback as well!

2020-10-15 14:46 UTC, nworb95 commented
Hey @sduenas -- I made the changes requested, let me know how to make the tests pass!

2020-10-23 10:23 UTC, sduenas commented
> Hey @sduenas -- I made the changes requested, let me know how to make the tests pass!

@nworb95 the PR looks ok to me. The problem with the tests is something related with a dependency that doesn't work anymore. I'll try to check it this weekend and try to fix it.

2020-11-13 17:54 UTC, closed without merging

2020-11-13 17:54 UTC, sduenas commented
@nworb95 thanks for the patch, I've just merged it into master once that we fixed the internal problems with the test suite.