Disables stack trace if debug flag is absent
chaoss/grimoirelab-perceval pull request #725
Opened 2021-03-28 17:44 UTC by AllMight2099

Fixes #692 

I'm passing in a bool flag (`debug_check`) in the constructor for the `BackendCommand` class, and setting the `logger` package's exception's function parameter `exc_info=debug_check`. The stack trace only gets printed if the debug flag (`-g`) gets passed in, which would mean that the `debug_check` variable is `True`.
This commit uses `logger`'s exception function to raise an exception.

Signed-off-by: Nishanth <nishusheela2011@gmail.com>

2021-03-30 09:13 UTC, sduenas requested changes
Thanks for your contribution. Please check my comments and also try to create a commit following the [contributing guidelines](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages). You should add some body to the commit message and tag the title of your message with `[backend]`

2021-03-30 09:13 UTC, sduenas commented on perceval/backend.py
> +    def __init__(self, *args, debug_check=False):
I think you can rename the parameter to `debug`, which is probably more clear. Also would you mind to add this parameter in the documentation of the class, so people know what to expect? Some examples here: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L65

2021-03-30 16:03 UTC, AllMight2099 commented
Lemme just do that

2021-03-30 18:46 UTC, AllMight2099 commented
I guess you should be able to test it now @sduenas

2021-03-31 09:12 UTC, sduenas requested changes
Sorry, the body of the message is wrong. When you _squashed_ it, you forgot to remove one of the messages of the commit. Also, it references the old name of the parameter. Please change it and we can merge it.

2021-03-31 09:16 UTC, AllMight2099 commented
@sduenas How about now?

2021-03-31 10:11 UTC, sduenas approved these changes
LGTM

2021-03-31 10:15 UTC, closed without merging