[docs] Expand docs for implementing new backends
chaoss/grimoirelab-perceval pull request #738
Opened 2021-06-18 17:37 UTC by Alch-Emi

Using the current documentation, it can be pretty difficult to learn how to appropriately implement a new backend for perceval.  Many of the methods that backends are supposed to implement have no documentation explaining what the methods are supposed to do, or even how their arguments are formatted.

Although it is possible to reverse engineer this information from other backends, this process is time consuming, frustrating, and may deter new developers from being able to use perceval with their application.

This commit expands documentation relating to implementing new backends in several ways:

- The class-level documentation for backends has been expanded to list more of the necessary methods and attributes that backends are responsible for implementing, and additionally lists a brief summary of each method.
- Several methods which were previously not listed (_init_client), or listed as optional (metadata_*) have been listed as mandatory.  As far as I can tell, there is no way to create a working backend without implementing these methods, or at least stubbing them.
- Information about class attributes in the class-level documentation has been replaced with a brief summary and a link, with the full text being moved to the attribute itself, making the class-level documentation easier to digest.
- Some of the documentation for class attributes that was sparse or missing altogether has been added
- All* methods and class attributes that are intended to be implemented by subclasses of `Backend` have detailed documentation describing exactly what is expected of the implementor, and giving context for some of the terms or argument names used where necessary.
- Some references to other methods and class attributes in the docs have been converted to links, to make navigating the docs easier.

Some important notes:

- The documentation for `has_resuming` has been left blank.  Despite my efforts, I wasn't able to determine what this was meant to indicate, and could find no examples of it being used in context with which to reverse engineer its purpose.  If someone is able to fill me in on what this method does, I would be happy to add documentation in.
- I haven't been working with perceval very long, and most of the knowledge I am contributing here is based on experimentation, reverse engineering, my own experiences working on perceval-osf, and extrapolating from what documentation existed before hand.  It's very possible that I've made a mistake in describing some of these methods, so please review carefully to make sure I am correct.  If I've made any mistakes, I will be happy to be corrected, and revise my mistake quickly after.

If you have any other advice, or recommended changes, I would be happy to hear!

2021-06-20 17:03 UTC, sduenas commented
@Alch-Emi thanks for you PR, this is awesome. I'll review it tomorrow!

2021-06-28 11:09 UTC, sduenas requested changes
Thanks for your contribution. It's awesome. I added some suggestions to keep the format aligned with the style in the docstrings. Please change your PR and we can merge it. Don't forget to squash your commit and a single one and rebase it with master. Thanks!

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        """ Produce a unique identifier for an item
```suggestion
        """Produce a unique identifier for an item.
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        unique identifier for that item.  Typically, this is an identifier
```suggestion
        unique identifier for that item. Typically, this is an identifier
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        The id should be represented by a string
```suggestion
        The id should be represented by a string.
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        """ Determine the last time an item was updated
```suggestion
        """Determine the last time an item was updated.
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        """ Identify the category of a given item
```suggestion
        """Identify the category of a given item.
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        of the categories listed in the `CATEGORIES` class member.  This method
```suggestion
        of the categories listed in the `CATEGORIES` class member. This method
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        """ Initialize the client to be used by the backend
```suggestion
        """Initialize the client to be used by the backend.
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        a backend.  This method is called before any calls to
```suggestion
        a backend. This method is called before any calls to
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        or `return None`.  However, note that the `.client` attribute will
```suggestion
        or return `None`. However, note that the `.client` attribute will
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        still be overridden
```suggestion
        still be overridden.
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        ignored.
```suggestion
        Additionally, the client or the backend should be set to respect
        archiving, based on the :func:`from_archive`. If the backend does not
        report that it :func:`has_archiving`, then this parameter may just be
        ignored.
```

2021-06-28 11:09 UTC, sduenas commented on perceval/backend.py
> +        :returns: A client, or `None`
```suggestion
        :returns: a client, or `None`
```

2021-06-28 11:26 UTC, sduenas commented
>     * The documentation for `has_resuming` has been left blank.  Despite my efforts, I wasn't able to determine what this was meant to indicate, and could find no examples of it being used in context with which to reverse engineer its purpose.  If someone is able to fill me in on what this method does, I would be happy to add documentation in.
> 
@Alch-Emi it's hard to explain but I'll try to do it.

A backend has resuming or the fetching process can be resumed if when it stops, either because it failed or because there aren't more items to retrieve, items can be retrieved again from the point it stopped without data loss.

For example, if the `github` backend fails and it's retrieving data from `chaoss/grimoirelab-elk` repository, I can run again it using the last date of the last item it retrieved and run it again using this date as `from-date` parameter. The backend will start retrieving data from that date and we're sure that there's no a gap of data it didn't retrieve. This doesn't happen with `gerrit` backend.

In gerrit, data is retrieved internally from newest to oldest. If the process fails, it means it has to start from the newest item to retrieve everything it wasn't retrieved before. This newest item can be newer than the first time it run because these items could have been produced while the backend was running. If it fails again the problem becomes bigger because you might have two gaps of information that you didn't retrieve.

It's a bit confusing. I hope you understood it.

2021-07-27 01:33 UTC, Alch-Emi commented
I just pushed a commit with your changes!  I really need to unlearn typing double spaces, but I've been doing it since elementary school at this point, and old habits die hard, I guess 😅

I tried writing up the `has_resuming` docs as well, but I recommend you give it a look over to make sure I got everything right.

Thanks so much for the review!

2021-07-27 12:08 UTC, sduenas commented on perceval/backend.py
> +    Note:  Origin in this context refers to one site, api, or other remote that
@Alch-Emi this is the only double space you forgot to fix, can you do it?

2021-07-27 12:22 UTC, Alch-Emi commented on perceval/backend.py
> +    Note:  Origin in this context refers to one site, api, or other remote that
Oh thank you!

2021-07-27 17:08 UTC, sduenas approved these changes
LGTM

2021-07-27 17:14 UTC, merged

2021-07-27 17:14 UTC, sduenas commented
@Alch-Emi thank you so much for your contribution!