[Git] Add argument `base-path` for git backend
chaoss/grimoirelab-perceval pull request #759
Opened 2021-09-07 14:41 UTC by xiao623

This code adds argument `base-path` for git backend to decide path where the Git repositories will be cloned.

Version updated to 0.12.1

Fixes #758 

Signed-off-by: Fugang Xiao <xiao623@outlook.com>

2021-09-08 07:15 UTC, vchrombie commented
Hi @xiao623, thanks for the PR.
It would be great if you can add a test for the feature you have added along with this PR. You can check the tests for the git backend here [tests/test_git.py](https://github.com/chaoss/grimoirelab-perceval/blob/master/tests/test_git.py). This would fix the coverage check.

Please let me know if you need any help.

2021-09-08 11:04 UTC, vchrombie commented
Thank you @xiao623 for adding the tests. As a final step, can you squash the commits into one and give a combined commit message?

Please see the commit description should be wrapped at 72 characters as per the [guidelines](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages).

Example
```
[git] Add argument base-path for the git backend

This code adds the argument `base-path` for the git backend 
to decide the path where the Git repositories will be cloned. 
Tests have been added accordingly.

The backend version updated to 0.12.1
```

It would be great if you can rebase your branch before the final force push.

Please let me know if you need help.

2021-09-08 11:27 UTC, vchrombie commented
Great work! Thanks a lot, @xiao623.
I would leave the PR to @sduenas for further review.

2021-09-08 11:30 UTC, xiao623 commented
Thanks. @vchrombie

2021-09-09 09:22 UTC, sduenas requested changes
Thanks for your patch. Very useful. However, would you mind to check my suggestions?

2021-09-09 09:22 UTC, sduenas commented on perceval/backends/core/git.py
> +        elif self.parsed_args.base_path:
I think the full `if` block can be reduced to the next code. Thus, we don't repeat ourselves. What do you think?

```
if self.parsed_args.git_log:
    git_path = self.parsed_args.git_log
elif self.parsed_args.git_path:
    git_path = self.parsed_args.git_path
else:
    if self.parsed_args.base_path:
        base_path = self.parsed_args.base_path
    else:
        base_path = os.path.expanduser('~/.perceval/repositories/')   

    processed_uri = self.parsed_args.uri.lstrip('/')
    git_path = os.path.join(base_path, processed_uri) + '-git'
```

2021-09-09 09:22 UTC, sduenas commented on tests/test_git.py
> +        self.assertEqual(cmd.parsed_args.gitpath, '/tmp/basepath/http://example.com/' + '-git')
Is there any problem with this other form?
```suggestion
        self.assertEqual(cmd.parsed_args.gitpath, '/tmp/basepath/http://example.com/-git')
```

2021-09-09 12:41 UTC, sduenas approved these changes
LGTM

2021-09-09 12:44 UTC, sduenas requested changes
Last one thing @xiao623 , can you rebase this PR to master before we merge it?

2021-09-10 12:27 UTC, vchrombie commented
Hi @xiao623, could you please rebase the PR again?
We are really sorry for the inconvenience caused.

2021-09-11 01:04 UTC, xiao623 commented
It is okay. @vchrombie

2021-09-11 06:55 UTC, vchrombie commented
I think we can merge the PR.
@sduenas what do you say?

2021-09-11 10:13 UTC, merged

2021-09-11 10:20 UTC, vchrombie commented
Thanks for your contribution @xiao623. :tada: