Document GitLab backend usage
chaoss/grimoirelab-perceval pull request #803
Opened 2022-09-30 19:11 UTC by xurizaemon

There is no documentation for the GitLab data source. This is based off the GitHub docs but I've reviewed it and believe it is correct for GitHub.

This PR would need updating if #801 landed first, and I will update whichever is required when one or the other lands 😁

2022-10-03 13:34 UTC, sduenas requested changes
The PR looks good to me but you will have to update it because we merged #801, so there are some conflicts. This PR doesn't need an entry in the changelog, so you can remove it.

Thanks for the PR.

2022-10-03 20:01 UTC, xurizaemon commented
Great, will do! Thanks.

2022-10-03 21:04 UTC, xurizaemon commented
Hi @sduenas - rebased and removed PR, which has caused the check-changelog check to fail as it should 😁

2022-10-03 21:08 UTC, xurizaemon commented
Sidebar: Is that Coveralls check accurate? I'm not clear how this PR seemed to at first increase, and now decrease, coverage. But I'm not familiar with Coveralls so my expectation that it reflects test coverage vs LoC may be incorrect.

2022-10-06 14:03 UTC, sduenas approved these changes
LGTM

2022-10-06 14:39 UTC, sduenas approved these changes
LGTM (I squashed the commits to make the history cleaner).

2022-10-06 14:41 UTC, sduenas commented
> Sidebar: Is that Coveralls check accurate? I'm not clear how this PR seemed to at first increase, and now decrease, coverage. But I'm not familiar with Coveralls so my expectation that it reflects test coverage vs LoC may be incorrect.

Unless the change of coverage is big, I usually ignore it. Sometimes it doesn't calculate very well small changes or when there aren't changes at all.

2022-10-06 15:02 UTC, closed without merging

2022-10-06 15:02 UTC, sduenas commented
Merged

2022-10-06 15:03 UTC, sduenas commented
Thanks for your contribution @xurizaemon