Confluence token authentication
chaoss/grimoirelab-perceval pull request #824
Opened 2023-09-22 06:05 UTC by zhifeiyue

Support token authentication for Confluence backend.

For Confluence Data Center or server editions, just use the personal access token:
`perceval confluence 'http://[YOUR_CONFLUENCE_SITE]/' -t [PERSONAL_ACCESS_TOKEN]`

For Confluence cloud:
`perceval confluence -u 'someone@example.com' -t [API_TOKEN] 'https://[YOUR_SITE].atlassian.net/wiki'`

2023-09-28 12:03 UTC, sduenas requested changes
Thanks so much for your PR. Would you mind to address my comments?

2023-09-28 12:03 UTC, sduenas commented on releases/unreleased/add-token-auth-for-confluence.yml
> +    Add token authentication to the Confluence backend.
```suggestion
    Authentication in `confluence` backend is supported using
    personal access tokens. Confluence Data Center and server
    editions 7.9 and later can use personal access tokens without
    a username. For Confluence Cloud, username and token are required.
```

2023-10-11 03:23 UTC, zhifeiyue commented on perceval/backends/core/confluence.py
> +                 user=None, api_token=None):
ok, I will add the docstring and increase the version number.

2023-10-11 03:27 UTC, zhifeiyue commented on perceval/backends/core/confluence.py
> +                 user=None, api_token=None):
Ok. Thanks for your review, I will update the docstring today.

2023-10-11 13:49 UTC, zhifeiyue commented
> It looks good to me but, before we merge it, would you mind to squash the commits into a single one and sign it?

ok, I just finished it.

2023-10-13 09:22 UTC, sduenas approved these changes
LGTM

2023-10-13 09:22 UTC, merged

2023-10-13 09:23 UTC, sduenas commented
Thanks for your contribution!