Adding deletion for old tag references
chaoss/grimoirelab-perceval pull request #845
Opened 2024-06-28 15:43 UTC by mjgaughan

title: 'Adding deletion for old tag references'
category: fixed
author: Matt Gaughan <mgaughan@proton.me>
issue:  (782)[https://github.com/chaoss/grimoirelab-perceval/issues/782]
notes: >
    If server deletes reference to tag, local repo will as well. 
    Simple implementation for clarity's sake.

2024-07-02 03:25 UTC, mjgaughan commented
@jjmerchante hello! Thank you for your help with sorting out this PR -- when I run_tests.py on my local, there are a handful of errors in unrelated tests. I'm not sure how many of these are a function of the changes that I have made, which I regard as small. Please let me know if I'm breaking something in a way I don't anticipate -- still getting familiar with the broader code base architecture!

2024-07-02 07:57 UTC, sduenas commented
> @jjmerchante hello! Thank you for your help with sorting out this PR -- when I run_tests.py on my local, there are a handful of errors in unrelated tests. I'm not sure how many of these are a function of the changes that I have made, which I regard as small. Please let me know if I'm breaking something in a way I don't anticipate -- still getting familiar with the broader code base architecture!

The current errors in the tests are because you aren't following the code style defined by `flake8` in your test file.

2024-08-13 19:49 UTC, vchrombie requested changes
Hi @mjgaughan, these changes should fix the errors in the test.

It would be great if you can squash these commits into one and add a changelog file as required. Please let me know if you need any help to get this PR merged.

2024-08-13 19:49 UTC, vchrombie commented on tests/test_git.py
> +        self.assertListEqual(refs, expected)
```suggestion
        # Verify that the new tag 'v.0.0-lw' exists in the refs
        refs = discover_refs(new_path)
        self.assertIn('refs/tags/v.0.0-lw', refs)
```

2024-08-13 19:49 UTC, vchrombie commented on tests/test_git.py
> +        self.assertListEqual(refs, expected)
```suggestion
        # Verify that the tag 'v.0.0-lw' is no longer in the refs
        refs = discover_refs(new_path)
        self.assertNotIn('refs/tags/v.0.0-lw', refs)
        self.assertIn('refs/heads/master', refs)

```

2024-08-14 03:52 UTC, mjgaughan commented
@vchrombie Thank you for your help with this PR and for the useful suggestions in code review. I have implemented your changes to test as well as added a changelog file. Please let me know if there are any other steps to merging.

2024-08-14 12:18 UTC, vchrombie commented
Hi @mjgaughan, thanks for working on this. As a final step, can you squash all these commits into one? Let me know if you need any help.

2024-08-15 20:10 UTC, mjgaughan commented
Hey @vchrombie I just squashed the commits; let me know if it looks ok! Thanks so much for your help with this

2024-08-20 16:20 UTC, sduenas commented
Can you edit the commit message? It has multiple lines with the signed off trailer and also it doesn't describe what you did on this commit. Please also start the first line with `[git] Add deletion of old tag references`.

2024-08-20 21:26 UTC, mjgaughan commented
@vchrombie @sduenas Just updated the commit message to meet what I believe is specification. Please let me know if there are any errors. Thanks!

2024-08-21 07:49 UTC, merged